#ifndef IMU_H
#define IMU_H

#include "Eris.h"

#include <Arduino.h>
#include <eris_sensor.h>   // ERIS_SENSOR_MULTI

namespace IMU{

// Generated by ERIS_SENSOR_MULTI in imu.cpp: one buffer per device.
extern ErisBuffer<IMUSample_t> buffer[];
extern int failures;

void begin(void);     // Wire + device bring-up, then start()
void start(void);     // generated: creates the buffers and the polling thread
void InitIMU(void);   // re-run device bring-up (INITIMU command)

}

#endif
