// Eris is a firmware that handles low level control
// It is based on RTOS and ported to Arduino
//
// ErisStepper: one stepper axis behind a TMC2209.
//   STEP/DIR  -> motion       (motion.cpp)
//   UART      -> configuration and diagnostics (tmc2209.cpp)
//   G0        -> the command surface (gcode.cpp)

#include "configuration.h"
#include "Eris.h"
#include "motion.h"
#include "tmc2209.h"
#include "gcode.h"
#include <modules/heartbeat.h>
#include <modules/sinewave.h>
#include "serialcommands.h"

const char firmwareInfo[]=FIRMWARE_INFO;


void start(){
  eriscommon::setPrintPacketMode(true); //send prints to eris

  /*************** Start Threads ************************/
  Heartbeat::start();
  Error::start(); // Start error notification task (Do not disable)

  t0=micros();

  // start special tasks from external sources
  SineWave::start();

  // Order matters: the UART decides how many microsteps one STEP pulse is
  // worth, so configure the driver before anything can pulse it.
  TMC::begin();
  Motion::begin();
  Stepper::start();   // axis telemetry (generated by ERIS_SENSOR in motion.cpp)

  // Serial command interface
  SerialCom::start();

  // Boot streaming the axis as plain text, so plugging the board in and
  // opening the Serial Monitor (or Plotter) shows position/velocity/target
  // with nothing typed. The Python driver sends "S_MODE BIN" on connect to
  // switch to the binary protocol.
  SerialCom::bootDefaults("STEP", true);
}

void setup(){
  Serial.begin(ERIS_SERIAL_BAUD);
  // Wait for USB Serial.
  while (!Serial) {}
  delay(1000);
  // Setup the initial configuration
  Serial.println("HELLO, This is Eris");
  /*************** Configure HW pins *******************/
  pinMode(PIN_LED,OUTPUT);
  digitalWrite(PIN_LED,LOW);
  /******************************************************/

  //Start threads
  ERIS_RUN(start);
}




void loop(){
    eris_sleep_ms(10000);
}
