#ifndef MOTION_H
#define MOTION_H

#include <Arduino.h>

#include "Eris.h"
#include <eriscommon.h>
#include <eris_sensor.h>   // ERIS_SENSOR (telemetry)

/*
 * Motion: the STEP/DIR half of the axis.
 *
 * Everything here is in millimetres at the edges and in steps on the inside.
 * STEPPER_STEPS_PER_MM is the only conversion, and it lives in configuration.h
 * because it is a property of the machine, not of the code.
 *
 * There is no homing and no limit switch in this flavor: position 0 is wherever
 * the axis happened to be at power-up, or wherever ZERO was last issued.
 */
namespace Motion{

void begin(void);                 // configure pins, start the motion thread

// G-code entry points ------------------------------------------------------
// moveTo() is what G0 X<mm> calls; it returns false when the target is outside
// the soft limits, and moves nothing in that case.
bool  moveTo(float mm);
// Feedrate in mm/min, the G-code F word. Clamped to [STEPPER_MIN_FEED,
// STEPPER_MAX_FEED]; returns the value actually adopted.
float setFeed(float mmPerMin);
float feed(void);

// Manual control -----------------------------------------------------------
void  stop(void);                 // decelerate to a halt at the current rate
void  zero(void);                 // call the current position 0 mm
void  enable(bool on);            // energize / release the motor

// State --------------------------------------------------------------------
float positionMm(void);
float targetMm(void);
float velocityMmS(void);          // signed: negative means travelling toward -X
bool  isMoving(void);
bool  isEnabled(void);

// Hard-stop detection ------------------------------------------------------
/*
 * Backed by StallGuard4, not by a current threshold: a chopper driver holds
 * coil current constant, so hitting a hard stop does not raise it. SG_RESULT
 * measures the load angle instead and falls toward zero as the rotor is pushed
 * out of sync -- see the block comment in configuration.h.
 *
 * Two things have to be true before a low reading is believed: the axis is
 * moving at STEPPER_STALL_MIN_FEED or faster, and the move has been running
 * for STEPPER_STALL_ARM_MS. Without both gates every move trips on its own
 * acceleration ramp.
 */
bool  stallArmed(void);           // are the gates satisfied right now
void  notifyStall(void);          // latch a stall (and halt, if configured)
bool  stalled(void);              // the latch
void  clearStall(void);           // acknowledge; a new G0 does this too
// Runs once per telemetry sample, on the telemetry thread: polls SG_RESULT
// when DIAG is not wired, and reports a latched stall. Returns the SG value to
// put in the sample.
uint16_t stallService(void);

}

/*
 * Axis telemetry, generated by ERIS_SENSOR in motion.cpp. It samples the state
 * the motion thread maintains -- there is no device to read, which is exactly
 * the case ERIS_SENSOR handles best.
 */
namespace Stepper{
extern ErisBuffer<StepperSample_t> buffer;
void start(void);
}

#endif
